/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponentDyn {}
  interface MyComponentDynAttributes extends StencilHTMLAttributes {}

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponentDyn': Components.MyComponentDyn;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-component-dyn': Components.MyComponentDynAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyComponentDynElement extends Components.MyComponentDyn, HTMLStencilElement {}
  var HTMLMyComponentDynElement: {
    prototype: HTMLMyComponentDynElement;
    new (): HTMLMyComponentDynElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-component-dyn': HTMLMyComponentDynElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-component-dyn': HTMLMyComponentDynElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
